name: Flutter Android Build

on:
  push:
    branches:
      - main # مطمئن شوید این branch درست است

jobs:
  build:
    runs-on: ubuntu-latest # سیستم عاملی که بیلد روی آن اجرا می شود

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # برای دسترسی به کدها در Workflow

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # JDK 17 برای فلاتر توصیه می شود

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4' # نسخه دقیق Flutter
          channel: 'stable'

      # مسیر Android SDK را تنظیم می کنیم
      - name: Define Android SDK Root
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/Android/sdk" >> $GITHUB_ENV
          echo "$HOME/Android/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/Android/sdk/platform-tools" >> $GITHUB_PATH

      - name: Install Android SDK platforms and build tools
        run: |
          # نصب cmdline-tools به صورت دستی
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8583023_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm cmdline-tools.zip
          
          # پذیرش لایسنس های Android SDK به صورت خودکار
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # نصب پلتفرم ها و ابزارهای بیلد
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Restore Flutter packages
        run: flutter pub get # دریافت پکیج های پروژه

      # - name: Decode Google Services (Optional for Firebase)
      #   if: ${{ secrets.GOOGLE_SERVICES_JSON != '' }}
      #   run: |
      #     echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json

      - name: Build Android APK
        run: flutter build apk --release # بیلد نسخه APK

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
              name: app-release-apk
              path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build Android AppBundle
        run: flutter build appbundle --release # بیلد نسخه AppBundle

      - name: Upload AppBundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab
