name: Flutter Android Build # نام Workflow که در GitHub Actions نمایش داده می شود

on:
  push:
    branches:
      - main # این Workflow با هر push به branch 'main' اجرا می شود.
              # اگر branch اصلی شما 'master' است، آن را به 'master' تغییر دهید.
  workflow_dispatch: # این به شما اجازه می دهد که Workflow را به صورت دستی از رابط کاربری GitHub Actions اجرا کنید.

jobs:
  build:
    runs-on: ubuntu-latest # Workflow روی یک ماشین مجازی لینوکس (اوبونتو) اجرا می شود.

    steps:
      - name: Checkout code # مرحله اول: دانلود کدهای پروژه از مخزن GitHub
        uses: actions/checkout@v4

      - name: Set up Java # مرحله دوم: نصب و تنظیم Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # توزیع Temurin از JDK (توصیه شده)
          java-version: '17'      # نسخه JDK مورد نیاز (JDK 17 برای فلاتر توصیه می شود)

      - name: Set up Flutter # مرحله سوم: نصب و تنظیم Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4' # نسخه دقیق Flutter SDK که پروژه شما با آن کار می کند
          channel: 'stable'         # استفاده از کانال stable (پایدار) فلاتر

      - name: Configure Android SDK Path and Install Components # مرحله چهارم: تنظیم PATH و نصب کامپوننت ها
        run: |
          # اطمینان از تنظیم ANDROID_HOME توسط flutter-action (یا یک مسیر پیش فرض)
          echo "ANDROID_HOME: $ANDROID_HOME" # نمایش مسیر ANDROID_HOME برای debugging
          
          # اضافه کردن مسیر cmdline-tools/latest/bin به PATH برای اجرای sdkmanager
          # flutter-action معمولا cmdline-tools را در $ANDROID_HOME/cmdline-tools/latest/bin قرار می دهد
          # این مسیر را به PATH فعلی اضافه می کنیم تا sdkmanager پیدا شود.
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
          echo "PATH after adding cmdline-tools: $PATH" # نمایش PATH جدید برای debugging

          # پذیرش لایسنس های Android SDK به صورت خودکار
          # '|| true' باعث می شود که اگر خطایی در پذیرش لایسنس ها رخ داد، Workflow متوقف نشود.
          yes | sdkmanager --licenses || true
          
          # نصب پلتفرم اندروید 34، ابزارهای بیلد 34.0.0 و platform-tools
          # (platform-tools به صورت مستقل هم نصب می شود تا از وجود آن اطمینان حاصل شود)
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Restore Flutter packages # مرحله پنجم: دریافت و بازیابی پکیج های Dart/Flutter
        run: flutter pub get

      # - name: Decode Google Services (Optional for Firebase)
      #   # این مرحله اگر پروژه از Firebase استفاده می کند و شما GOOGLE_SERVICES_JSON را به عنوان Secret تعریف کرده اید، اجرا می شود.
      #   # در حال حاضر، این بخش غیرفعال (کامنت شده) است. اگر نیاز داشتید، علامت # را از ابتدای خطوط حذف کرده و Secret را تعریف کنید.
      #   if: ${{ secrets.GOOGLE_SERVICES_JSON != '' }}
      #   run: |
      #     echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json

      - name: Build Android APK # مرحله ششم: ساخت فایل APK نسخه Release
        run: flutter build apk --release

      - name: Upload APK artifact # مرحله هفتم: آپلود فایل APK ساخته شده به عنوان Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build Android AppBundle # مرحله هشتم: ساخت فایل AppBundle نسخه Release (برای انتشار در Google Play)
        run: flutter build appbundle --release

      - name: Upload AppBundle artifact # مرحله نهم: آپلود فایل AppBundle ساخته شده به عنوان Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab
