name: Flutter Android Build

on:
  push:
    branches:
      - main # مطمئن شوید این branch درست است

jobs:
  build:
    runs-on: ubuntu-latest # سیستم عاملی که بیلد روی آن اجرا می شود

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # برای دسترسی به کدها در Workflow

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4' # نسخه دقیق Flutter که در doctor شما بود
          channel: 'stable'

      - name: Install Android SDK platforms and build tools
        run: |
          # نصب پلتفرم 34، ابزارهای بیلد 34.0.0 و آخرین Command-line tools
          yes | sdkmanager "platforms;android-34" "build-tools;34.0.0" "cmdline-tools;latest"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # JDK 17 برای فلاتر توصیه می شود

      - name: Restore Flutter packages
        run: flutter pub get # دریافت پکیج های پروژه

  #    - name: Decode Google Services (Optional for Firebase)
        # این مرحله اگر از Firebase استفاده می کنید و GOOGLE_SERVICES_JSON را به عنوان Secret تعریف کرده اید، اجرا می شود.
     #   if: ${{ secrets.GOOGLE_SERVICES_JSON != '' }}
   #     run: |
     #     echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json

      - name: Build Android APK
        run: flutter build apk --release # بیلد نسخه APK

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build Android AppBundle
        run: flutter build appbundle --release # بیلد نسخه AppBundle

      - name: Upload AppBundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab
